export const MARKETS: string[] = [
  'Abilene, TX',
  'Akron, OH',
  'Albuquerque, NM',
  'Allen, TX',
  'Anderson, SC',
  'Ankeny, IA',
  'Ann Arbor, MI',
  'Annapolis, MD',
  'Aptos, CA',
  'Arlington, TX',
  'Arlington, VA',
  'Asheville, NC',
  'Aurora, CO',
  'Bakersfield, CA',
  'Battle Creek, MI',
  'Bend, OR',
  'Birmingham, AL',
  'Bloomington, MN',
  'Bluffton, SC',
  'Bozeman, MT',
  'Bradenton, FL',
  'Branson, MO',
  'Brea, CA',
  'Broken Arrow, OK',
  'Bronx, NY',
  'Brownsburg, IN',
  'Bryan, TX',
  'Buffalo, NY',
  'Burlington, NC',
  'Caldwell, ID',
  'Camp Verde, AZ',
  'Canby, OR',
  'Cantonment, FL',
  'Carbondale, KS',
  'Casper, WY',
  'Cedar Rapids, IA',
  'Charlotte, NC',
  'Chattanooga, TN',
  'Cheyenne, WY',
  'Chicago, IL',
  'Cincinnati, OH',
  'Clarkdale, AZ',
  'Clarksville, TN',
  'Clearwater, FL',
  'Cleveland, OH',
  "Coeur d'Alene, ID",
  'Colorado Springs, CO',
  'Columbia, MD',
  'Columbia, SC',
  'Columbus, OH',
  'Concord, NH',
  'Cranston, RI',
  'Crescent City, CA',
  'Dallas, TX',
  'Davenport, IA',
  'Dayton, OH',
  'Del Mar, CA',
  'Denver, CO',
  'Detroit, MI',
  'Dothan, AL',
  'Dover, DE',
  'Dripping Springs, TX',
  'Duluth, MN',
  'Durham, NC',
  'Eagle, ID',
  'Edgewood, NM',
  'El Paso, TX',
  'Elgin, IL',
  'Elmira, NY',
  'Erie, PA',
  'Evanston, IL',
  'Fall River, MA',
  'Farmington, CT',
  'Fayetteville, AR',
  'Flint, MI',
  'Fort Lauderdale, FL',
  'Fort Myers, FL',
  'Fort Wayne, IN',
  'Fort Worth, TX',
  'Friendswood, TX',
  'Frisco, TX',
  'Fulshear, TX',
  'Gadsden, AL',
  'Glen Burnie, MD',
  'Grand Rapids, MI',
  'Greenville, SC',
  'Gulf Shores, AL',
  'Gulfport, MS',
  'Harrisburg, PA',
  'Hartford, SD',
  'Hastings, MI',
  'Havelock, NC',
  'Hereford, TX',
  'Hershey, PA',
  'Hilo, HI',
  'Hot Springs, AR',
  'Indianapolis, IN',
  'Jacksonville, FL',
  'Jupiter, FL',
  'Kalispell, MT',
  'Kenosha, WI',
  'Knoxville, TN',
  'Lake Havasu City, AZ',
  'Lakeland, FL',
  'Lancaster, PA',
  'Las Vegas, NV',
  'Lebanon, IN',
  "Lee's Summit, MO",
  'Liberty Lake, WA',
  'Lincoln, NE',
  'Little River, SC',
  'Longboat Key, FL',
  'Louisville, KY',
  'Lubbock, TX',
  'Madison, WI',
  'Manchester, NH',
  'Maple Grove, MN',
  'Mariposa, CA',
  'Memphis, TN',
  'Miami, FL',
  'Milwaukee, WI',
  'Minneapolis, MN',
  'Monterey, CA',
  'Montgomery, TX',
  'Morganton, NC',
  'Mount Pleasant, SC',
  'Mountain View, CA',
  'Naples, FL',
  'New Braunfels, TX',
  'New York, NY',
  'Newark, NJ',
  'Norfolk, VA',
  'Northglenn, CO',
  'Oak Ridge, TN',
  'Ocala, FL',
  'Oceanside, CA',
  'Ogden, UT',
  'Omaha, NE',
  'Orlando, FL',
  'Oro Valley, AZ',
  'Palm Desert, CA',
  'Palm City, FL',
  'Park City, UT',
  'Pasadena, CA',
  'Pensacola, FL',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'Pittsburgh, PA',
  'Placerville, CA',
  'Port Saint Lucie, FL',
  'Portland, OR',
  'Providence, RI',
  'Raleigh, NC',
  'Reno, NV',
  'Richmond, VA',
  'Roanoke, VA',
  'Sacramento, CA',
  'Salt Lake City, UT',
  'San Antonio, TX',
  'San Diego, CA',
  'San Jose, CA',
  'Santa Rosa Beach, FL',
  'Scottsdale, AZ',
  'Seattle, WA',
  'Shawnee, OK',
  'Sioux Falls, SD',
  'Spartanburg, SC',
  'Springfield, MO',
  'St. Louis, MO',
  'St. Paul, MN',
  'Tampa, FL',
  'Tempe, AZ',
  'Thornton, CO',
  'Toledo, OH',
  'Topeka, KS',
  'Truckee, CA',
  'Tulsa, OK',
  'Tucson, AZ',
  'Union, SC',
  'Virginia Beach, VA',
  'Washington, DC',
  'Waukesha, WI',
  'West Chester, PA',
  'West Des Moines, IA',
  'West Fargo, ND',
  'Wilmington, NC',
  'Worcester, MA'
]