export const MARKETS: string[] = [
  'Columbus, OH','Cleveland, OH','Denver, CO','Memphis, TN','Minneapolis, MN',
  'Dayton, OH','Chicago, IL','Austin, TX','Cincinnati, OH','Grand Rapids, MI',
  'Milwaukee, WI','Philadelphia, PA','Akron, OH','Indianapolis, IN','Louisville, KY',
  'Manhattan, KS','San Antonio, TX','St. Louis, MO','Albuquerque, NM','Atlanta, GA',
  'Cedar Rapids, IA','Chattanooga, TN','Colorado Springs, CO','Houston, TX',
  'Kansas City, MO','Knoxville, TN','Phoenix, AZ','Seattle, WA','York, PA',
  'Detroit, MI','Anchorage, AK','Asheville, NC','Boise, ID','Des Moines, IA',
  'Fall River, MA','Greenville, SC','Little Rock, AR','Madison, WI','Nashville, TN',
  'North Charleston, SC','Oklahoma City, OK','Omaha, NE','Orlando, FL',
  'Palm Springs, CA','Pittsburgh, PA','Rochester, NY','Sacramento, CA',
  'Salt Lake City, UT','San Diego, CA','Tacoma, WA','Tampa, FL','Duluth, MN',
  'Kansas City, KS','Lancaster, PA','Las Vegas, NV','Logan, OH','Syracuse, NY',
  'Bend, OR','Boston, MA','Cambridge, MA','Charlotte, NC','Corvallis, OR',
  'Irvine, CA','Kalispell, MT','Scottsdale, AZ','Temecula, CA','Washington, DC',
  'Baltimore, MD','Bradenton, FL','Buffalo, NY','Clearwater, FL',
  'College Station, TX','Columbia, SC','Concord, NH','Dallas, TX',
  'Fayetteville, AR','Flint, MI','Fort Myers, FL','Fort Wayne, IN',
  'Fort Worth, TX','Fresno, CA','Gatlinburg, TN','Jacksonville, FL',
  'Leominster, MA','Lorain, OH','Miami, FL','Myrtle Beach, SC','New Bern, NC',
  'New Haven, CT','Norfolk, VA','Pottstown, PA','Providence, RI','Richmond, VA',
  'Roanoke, VA','Saint Augustine, FL','Saint Paul, MN','Santa Rosa Beach, FL',
  'Springfield, MA','Toledo, OH','Tulsa, OK','Yuma, AZ','Baldwin Park, CA',
  'Buena Vista, CO','Burbank, CA','Carmel-by-the-Sea, CA','Chandler, AZ',
  'Chino Hills, CA','Culver City, CA','East Los Angeles, CA','Eugene, OR',
  'Green Hill, TN','Hayward, CA','Laramie, WY','Lehi, UT','Lincoln Beach, OR',
  'Longmont, CO','Lowell, MA','Manor, TX','Menifee, CA','Oceanside, CA',
  'Roswell, GA','Salem, OR','Sandy, UT','Sarasota, FL','South Bend, IN',
  'Stowe, VT','Taunton, MA','Torrance, CA','Allentown, PA','Annapolis, MD',
  'Bardstown, KY','Bellevue, WA','Blue Ridge, GA','Bountiful, UT',
  'Boynton Beach, FL','Carbondale, PA','Carlsbad, CA','Carmichael, CA',
  'Charleston, SC','Clarksville, TN','Concord, CA','Cranston, RI','Destin, FL',
  'Dothan, AL','Durham, NC','Elgin, IL','Exton, PA','Farmington, CT',
  'Federal Way, WA','Glenview, IL','Grapevine, TX','Green Bay, WI','Greer, SC',
  'Gulf Shores, AL','Hartford, CT','Huntsville, AL','Incline Village, NV',
  'Iowa City, IA','La Grange, IL','La Mesa, CA','Livingston, CA','Long Beach, CA',
  'Manchester, NH','Miramar, FL','Monterey, CA','Mount Pocono, PA',
  'Neptune City, NJ','New Brunswick, NJ','New Hartford, CT','New Orleans, LA',
  'Newark, NJ','Norwich, CT','Ocala, FL','Oxford, CT','Palm Beach Gardens, FL',
  'Palo Alto, CA','Panama City Beach, FL','Pittsford, NY','Port Saint Lucie, FL',
  'Reno, NV','Reunion, FL','Riverside, CA','Rogers, AR','Rome, NY','Royal Oak, MI',
  'Scranton, PA','Seagrove Beach, FL','Skokie, IL','Spartanburg, SC',
  'Springfield, MO','The Woodlands, TX','Troy, OH','Tuscaloosa, AL',
  'Van Alstyne, TX','Virginia Beach, VA','Wakefield, MA','West Chester, PA',
  'Wheaton, IL','Whitefish, MT','Wildwood, MO','Wilmington, NC','Worcester, MA',
  'Auburn, IN','Augusta, GA','Bedford, VA','Binghamton, NY','El Paso, TX',
  'Endicott, NY','Fayetteville, NC','Fishers, IN','Greenville, NC',
  'Highland, MI','Hummelstown, PA','Jackson, MS','Johnson City, TN',
  'Kenosha, WI','Killeen, TX','La Crosse, WI','Lansing, MI','Ledyard, CT',
  'Newport News, VA','Ocean Springs, MS','Ottawa, IL','Pensacola, FL',
  'Reading, PA','Savannah, GA','Somers, CT','Swisher, IA','Tallahassee, FL',
  'Tinley Park, IL','West Milwaukee, WI','Worcester, PA','Auburn, WA',
  'Fortville, IN','Gainesville, FL','Gilbert, AZ','Greensboro, NC',
  'Limerick, PA','Queens, NY','Redlands, CA','Tucson, AZ','White Plains, NY',
]
